sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dxpzk1
        username: root
        password:
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dxpzk2
        username: root
        password:
    config:
#      masterslave:
#        master-data-source-name:
#        slave-data-source-names:
      sharding:
        props:
          sql.show: true
#        default-database-strategy:  #分库策略
#          hint:
#            algorithm-class-name: com.example.dxpzk.sharingRule.HintDatabaseShardingAlgorithm
        tables:
          user:  #user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds${0..1}.user
            database-strategy:  #分库策略
#              hint:
#                algorithm-class-name: com.example.dxpzk.sharingRule.HintDatabaseShardingAlgorithm
              inline:
                sharding-column: id
                algorithm-expression: ds${id % 2}
#            table-strategy:  #分表策略
#              inline:
#                shardingColumn: sex
#                algorithm-expression: t_user${sex % 2}
#          t_address:
#            key-generator-column-name: id
#            actual-data-nodes: ds${0..1}.t_address
#            database-strategy:
#              inline:
#                shardingColumn: lit
#                algorithm-expression: ds${lit % 2}

